from langchain_groq import ChatGroq
from langchain.agents import AgentExecutor, create_react_agent
from langchain.prompts import PromptTemplate
from langchain_core.prompts import ChatPromptTemplate
from app.tools import duckduckgo_search
from dotenv import load_dotenv
import os

load_dotenv()

REACT_PROMPT = PromptTemplate.from_template("""Answer the following questions as best you can. You have access to the following tools:

{tools}

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [{tool_names}]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!

Question: {input}
Thought:{agent_scratchpad}""")

REPORT_PROMPT = PromptTemplate.from_template("""
You are an expert research analyst. Based on the following web search findings about "{topic}",
write a comprehensive, well-structured research report.

Search Findings:
{findings}

Write the report in this EXACT format:

# Research Report: {topic}

## Executive Summary
[2-3 sentence overview]

## Key Findings
- [Finding 1]
- [Finding 2]
- [Finding 3]
- [Finding 4]
- [Finding 5]

## Detailed Analysis
[3-4 paragraphs of in-depth analysis]

## Current Trends
[What is currently happening in this space]

## Conclusion
[Summary and implications]

---
*Report generated by AI Research Agent*
""")


def create_agent():
    llm = ChatGroq(
        api_key=os.getenv("GROQ_API_KEY"),
        model_name="llama-3.1-8b-instant",
        temperature=0.3
    )
    tools = [duckduckgo_search]
    agent = create_react_agent(llm, tools, REACT_PROMPT)
    return AgentExecutor(
        agent=agent,
        tools=tools,
        verbose=True,
        max_iterations=5,
        handle_parsing_errors=True
    )


def run_research(topic: str) -> str:
    """Run the full research pipeline for a topic."""
    # Agent searches the web
    agent_executor = create_agent()
    search_result = agent_executor.invoke({
        "input": f"Search the web for detailed information about: {topic}. Find key facts, recent developments, statistics, and important details."
    })
    findings = search_result.get("output", "No findings available.")

    # Groq structures findings into a clean report
    llm = ChatGroq(
        api_key=os.getenv("GROQ_API_KEY"),
        model_name="llama-3.1-8b-instant",
        temperature=0.3
    )
    formatted_prompt = REPORT_PROMPT.format(topic=topic, findings=findings)
    report = llm.invoke(formatted_prompt)

    return report.content