import smtplib
import re
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
import os

load_dotenv()


def markdown_to_html(text: str) -> str:
    """Convert markdown report to clean HTML for email."""
    lines = text.split('\n')
    html_lines = []
    in_list = False

    for line in lines:
        # H1 heading  (#)
        if line.startswith('# '):
            if in_list:
                html_lines.append('</ul>')
                in_list = False
            html_lines.append(f'<h1>{line[2:].strip()}</h1>')

        # H2 heading  (##)
        elif line.startswith('## '):
            if in_list:
                html_lines.append('</ul>')
                in_list = False
            html_lines.append(f'<h2>{line[3:].strip()}</h2>')

        # H3 heading  (###)
        elif line.startswith('### '):
            if in_list:
                html_lines.append('</ul>')
                in_list = False
            html_lines.append(f'<h3>{line[4:].strip()}</h3>')

        # Bullet points (- item)
        elif line.startswith('- '):
            if not in_list:
                html_lines.append('<ul>')
                in_list = True
            content = line[2:].strip()
            content = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', content)
            html_lines.append(f'<li>{content}</li>')

        # Horizontal rule (---)
        elif line.strip() == '---':
            if in_list:
                html_lines.append('</ul>')
                in_list = False
            html_lines.append('<hr>')

        # Empty line
        elif line.strip() == '':
            if in_list:
                html_lines.append('</ul>')
                in_list = False
            html_lines.append('')

        # Regular paragraph
        else:
            if in_list:
                html_lines.append('</ul>')
                in_list = False
            content = line.strip()
            # Convert **bold** and *italic*
            content = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', content)
            content = re.sub(r'\*(.*?)\*', r'<em>\1</em>', content)
            if content:
                html_lines.append(f'<p>{content}</p>')

    if in_list:
        html_lines.append('</ul>')

    return '\n'.join(html_lines)


def build_html_email(topic: str, report_content: str) -> str:
    """Wrap report HTML in a clean, professional email template."""
    body_html = markdown_to_html(report_content)

    return f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body {{
    font-family: 'Segoe UI', Arial, sans-serif;
    background-color: #f4f6f9;
    margin: 0;
    padding: 0;
  }}
  .wrapper {{
    max-width: 680px;
    margin: 30px auto;
    background: #ffffff;
    border-radius: 10px;
    overflow: hidden;
    border: 1px solid #e0e4ea;
  }}
  .header {{
    background: linear-gradient(135deg, #1E3A5F, #2E6DB4);
    padding: 32px 36px;
    color: white;
  }}
  .header h1 {{
    margin: 0 0 6px;
    font-size: 22px;
    font-weight: 600;
    color: white;
  }}
  .header p {{
    margin: 0;
    font-size: 13px;
    color: #c8d8f0;
  }}
  .content {{
    padding: 28px 36px;
    color: #1a1a2e;
    line-height: 1.7;
  }}
  .content h1 {{
    font-size: 22px;
    color: #1E3A5F;
    border-bottom: 2px solid #2E6DB4;
    padding-bottom: 8px;
    margin-top: 0;
  }}
  .content h2 {{
    font-size: 17px;
    color: #2E6DB4;
    margin-top: 28px;
    margin-bottom: 8px;
    padding-left: 10px;
    border-left: 3px solid #2E6DB4;
  }}
  .content h3 {{
    font-size: 15px;
    color: #1E3A5F;
    margin-top: 20px;
  }}
  .content p {{
    font-size: 14px;
    color: #333344;
    margin: 10px 0;
  }}
  .content ul {{
    padding-left: 20px;
    margin: 10px 0;
  }}
  .content ul li {{
    font-size: 14px;
    color: #333344;
    margin-bottom: 6px;
  }}
  .content strong {{
    color: #1E3A5F;
  }}
  .content hr {{
    border: none;
    border-top: 1px solid #e0e4ea;
    margin: 24px 0;
  }}
  .footer {{
    background: #f4f6f9;
    padding: 18px 36px;
    font-size: 12px;
    color: #888899;
    text-align: center;
    border-top: 1px solid #e0e4ea;
  }}
  .topic-badge {{
    display: inline-block;
    background: #e8f0fb;
    color: #1E3A5F;
    font-size: 12px;
    padding: 4px 12px;
    border-radius: 20px;
    margin-top: 8px;
    font-weight: 500;
  }}
</style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h1>AI Research Report</h1>
      <p>Automated report generated by your AI Research Agent</p>
      <span class="topic-badge">{topic}</span>
    </div>
    <div class="content">
      {body_html}
    </div>
    <div class="footer">
      This report was automatically generated by AI Research Agent &bull;
      Powered by LangChain + Groq &bull; Do not reply to this email
    </div>
  </div>
</body>
</html>
"""


def send_report_email(topic: str, report_content: str, recipient: str) -> bool:
    """Send the research report as a formatted HTML email via Gmail SMTP."""
    sender = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")

    if not all([sender, password]):
        print("Email credentials not configured.")
        return False

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"Research Report: {topic}"
        msg["From"] = f"AI Research Agent <{sender}>"
        msg["To"] = recipient

        plain_text = report_content.replace('**', '').replace('##', '').replace('# ', '')
        text_part = MIMEText(plain_text, "plain", "utf-8")

        html_content = build_html_email(topic, report_content)
        html_part = MIMEText(html_content, "html", "utf-8")

        msg.attach(text_part)
        msg.attach(html_part)

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender, password)
            server.sendmail(sender, recipient, msg.as_string())

        print(f"HTML email sent successfully to {recipient}")
        return True

    except Exception as e:
        print(f"Email failed: {str(e)}")
        return False